### ISSUE TITLE
Calories deficit calculator

### ISSUE THREAD

**Issue by aetherfaye1009** [reactjsdevelopment/nextjs-basic#16]
Create a simple calorie deficit calculator that calculates the suitable amount of calories a user should consume.

**Comment by aetherfaye1009** [comment]
Kindly assign me the hacktoberfest tag if you are okay with it. Thank you.

**Comment by sunny7899** [comment]
Go ahead @aetherfaye1009

**Comment by JhoanAlvear** [comment]
Hello assigned to me , this issue please

**Comment by sunny7899** [comment]
@JhoanAlvear  I think @aetherfaye1009  is already working on this can you create a new issue.
