### ISSUE TITLE
Updating README.md file

### ISSUE THREAD

**Issue by HMSagar2701** [reactjsdevelopment/nextjs-basic#18]
Hi @sunny7899,

I would like to update the README.md file to reflect the latest changes, which will be helpful for future reference. I also have a query regarding the functionality of the application(What kind of app this one)—could you please provide more details? This will help us suggest potential improvements. Kindly assign this task to me. Thank you!

**Comment by sunny7899** [comment]
Go ahead @HMSagar2701
