### ISSUE TITLE
Issue with Footer 

### ISSUE THREAD

**Issue by HMSagar2701** [reactjsdevelopment/nextjs-basic#21]
Hi @sunny7899, Footer is reflecting twice as shown in the image, Please assign this issue I will work on it, Thanks

![image](https://github.com/user-attachments/assets/af1035ca-6522-47d9-ae69-c05c1efd7ce5)

**Comment by sunny7899** [comment]
Go ahead @HMSagar2701  please update the icon to react. its a react project.
