### ISSUE TITLE
Adding Features

### ISSUE THREAD

**Issue by HMSagar2701** [reactjsdevelopment/nextjs-basic#3]
Hi @sunny7899 , Please let me know what are the features can I work on this project Please assign the task to me add label hacktoberfest, thanks

**Comment by sunny7899** [comment]
Sure @HMSagar2701 . You can go through the app and see what you can improve in user experience and raise the PR

**Comment by definitelynotchirag** [comment]
@sunny7899 Can i add basic signin signup?

**Comment by HMSagar2701** [comment]
Hi @definitelynotchirag  I am working on that You can work on different components please

**Comment by definitelynotchirag** [comment]
@HMSagar2701 Can i work on adding tailwind or any other ui library? Our setting up a ORM like prisma?or firebase/supabase

**Comment by HMSagar2701** [comment]
Sure you can create a new issue for that ask maintainer to assign issue

**Comment by sunny7899** [comment]
@definitelynotchirag You can create a new issue for that will assign it to you.

**Comment by HMSagar2701** [comment]
Hi @sunny7899, I have raised PR related to this, Please check, Thanks
