### ISSUE TITLE
Setup Tailwind CSS configurations

### ISSUE THREAD

**Issue by definitelynotchirag** [reactjsdevelopment/nextjs-basic#5]
Add TailwindCSS to the Template

**Comment by sunny7899** [comment]
Go ahead @definitelynotchirag

**Comment by sunny7899** [comment]
@definitelynotchirag with the setup can u add its basic usage also that will be great. What's the benefit of tailwind. Add some demo in app.

**Comment by definitelynotchirag** [comment]
> @definitelynotchirag with the setup can u add its basic usage also that will be great. What's the benefit of tailwind. Add some demo in app.

Should i create a separate page for it?

**Comment by sunny7899** [comment]
Yes
